openapi: "3.1.0"
info:
  title: Игра Сапёр (Minesweeper)
  description: >-
    Спецификация АПИ <a href="/">игры Сапёр</a>.<br /><br />
    Каждая игра начинается с указания размера поля <code>width</code> и <code>height</code>, а также количества мин <code>mines_count</code> на нём. Исходная задача не подразумевает ограничений, но для тестовой реализации остановимся на разумном ограничении входных параметров: ширина и высота не более 30, количество мин не более <code>width * height - 1</code> (всегда должна быть хотя бы одна свободная ячейка).<br /><br />
    Далее игроку предлагается в созданной игре (идентификация игры по полученному в ответ <code>game_id</code>) делать ходы, указывая координаты ячейки, которую игрок хочет открыть, а именно - <code>row</code> (номер ряда, начиная с нуля) и <code>col</code> (номер колонки, начиная с нуля).<br /><br />
    В ответ на оба метода приходят данные о самой игре: уникальный идентификатор игры <code>game_id</code>, размер поля и количество мин, указанные при создании игры, а также данные о поле <code>field</code> в виде двумерного массива символов (<code>height</code> строк, в каждой по <code>width</code> элементов), где пустые строки <code>" "</code> (пробелы) означают неоткрытые ячейки поля, поля с цифрами от <code>"0"</code> до <code>"8"</code> означают открытые ячейки, где цифры указывают, сколько мин расположено в непосредственной близости от текущей ячейки. Также возвращается параметр <code>completed</code>, указывающий, завершена ли текущая игра.<br /><br />
    Игра заканчивается в случае, если пользователь указал на ячейку, где установлена мина (ячейки с минами при этом отмечены символом <code>"X"</code> - латинская заглавная "икс"), либо пользователь открыл все ячейки, не занятые минами (в этом случае мины отмечены <code>"M"</code> - латинская заглавная "эм"). Также при завершении игры должна появиться информация по всем остальным ячейкам - количество мин рядом с каждой из ячеек.<br /><br />
    Если в процессе игры пользователь открывает ячейку, рядом с которой нет ни одной мины (то есть ячейка со значением <code>"0"</code>), должны "открыться" все смежные ячейки, рядом с которыми также нет ни одной мины, а также все смежные с ними "числовые" ячейки, рядом с которыми мины есть, с указанием их количества.<br /><br />
    Не допускается после завершения игры делать новые ходы, а также повторно проверять уже проверенную ячейку. Эти, а также иные ошибочные ситуации должны возвращать ошибку с кодом <code>400 Bad Request</code> с текстовым описание ошибки в <code>error</code>.
  version: "1.0"
servers:
  - url: /api
    description: АПИ игры Сапёр
paths:
  /new:
    post:
      tags:
        - Minesweeper
      description: Начало новой игры
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewGameRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameInfoResponse"
        "400":
          description: Ошибка запроса или некорректное действие
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /turn:
    post:
      tags:
        - Minesweeper
      description: Ход пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameTurnRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameInfoResponse"
        "400":
          description: Ошибка запроса или некорректное действие
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    NewGameRequest:
      required:
        - width
        - height
        - mines_count
      properties:
        width:
          type: integer
          description: Ширина игрового поля
          example: 10
        height:
          type: integer
          description: Высота игрового поля
          example: 10
        mines_count:
          type: integer
          description: Количество мин на поле
          example: 10
    GameTurnRequest:
      required:
        - game_id
        - col
        - row
      properties:
        game_id:
          type: string
          description: Идентификатор игры
          format: uuid
          example: 01234567-89AB-CDEF-0123-456789ABCDEF
        col:
          type: integer
          description: Колонка проверяемой ячейки (нумерация с нуля)
          example: 5
        row:
          type: integer
          description: Ряд проверяемой ячейки (нумерация с нуля)
          example: 5
    GameInfoResponse:
      required:
        - game_id
        - width
        - height
        - mines_count
        - field
      properties:
        game_id:
          type: string
          description: Идентификатор игры
          format: uuid
          example: 01234567-89AB-CDEF-0123-456789ABCDEF
        width:
          type: integer
          description: Ширина игрового поля
          example: 10
        height:
          type: integer
          description: Высота игрового поля
          example: 10
        mines_count:
          type: integer
          description: Количество мин на поле
          example: 10
        completed:
          type: boolean
          description: Завершена ли игра
          example: false
        field:
          type: array
          description: Строки минного поля (количество равно высоте height)
          items:
            type: array
            description: Столбцы минного поля (количество равно ширине width)
            items:
              type: string
              enum:
                - " "
                - "0"
                - "1"
                - "2"
                - "3"
                - "4"
                - "5"
                - "6"
                - "7"
                - "8"
                - "M"
                - "X"
    ErrorResponse:
      properties:
        error:
          type: string
          description: Описание ошибки
          example: "Произошла непредвиденная ошибка"
      type: object
